### ISSUE TITLE
No errors shown with linter

### ISSUE THREAD

**Issue by chmac** [prettier/prettier-atom#235]
Excited to see the upgrade for inline error reporting. Saw #228. I have linter installed and enabled. But I don't see any errors at all from prettier, yet my code has a syntax error and so will not format.

Do I need to have linting enabled in this project or for this file or something like that?

In general, love the idea of the new approach, looks like there are maybe some kinks. Would it be feasible to add an option to enable the old style of error reporting? I guess the new approach introduces more dependencies which in turn increases complication / bug surface area. Will see if I can figure out how to downgrade in the meantime.

<details>
    Atom version: 1.18.0
    prettier-atom version: 0.36.1
    prettier version: 1.5.2
    prettier-eslint version: 6.4.2
    prettier-atom configuration: {
      "formatOnSaveOptions": {
        "enabled": true,
        "respectEslintignore": true,
        "showInStatusBar": false,
        "javascriptScopes": [
          "source.js",
          "source.jsx",
          "source.js.jsx",
          "source.babel",
          "source.js-semantic",
          "text.html.basic",
          "text.html.vue"
        ],
        "typescriptScopes": [
          "source.ts",
          "source.tsx",
          "source.ts.tsx"
        ],
        "cssScopes": [
          "source.css",
          "source.less",
          "source.css.less",
          "source.scss",
          "source.css.scss"
        ],
        "jsonScopes": [
          "source.json"
        ],
        "excludedGlobs": [],
        "whitelistedGlobs": [],
        "isDisabledIfNotInPackageJson": false
      },
      "prettierOptions": {
        "singleQuote": false,
        "bracketSpacing": true,
        "semi": true,
        "useTabs": false,
        "jsxBracketSameLine": false,
        "printWidth": 80,
        "tabWidth": "auto",
        "trailingComma": "none",
        "parser": "babylon"
      },
      "useEslint": false,
      "useEditorConfig": true,
      "prettierEslintOptions": {
        "prettierLast": false
      }
    }
</details>

**Comment by robwise** [comment]
Do you have the `linter` package installed and enabled?

**Comment by chmac** [comment]
> I have linter installed and enabled.

:-)

**Comment by robwise** [comment]
Oh my bad lol

good news, I was able to reproduce, working on a fix now

**Comment by robwise** [comment]
@darahak Are you able to reproduce this?

**Comment by chmac** [comment]
@robwise If there's anything I can do to help with testing / debugging, just let me know.

**Comment by robwise** [comment]
@chmac The weird thing is I'm having trouble reproducing. I wonder if it's specific to the source code or the project structure or something?

You can put your own print statements in and see what's going on.

```
apm develop prettier-atom
yarn install
yarn start build.watch
atom . --dev
```

Then reload your window from command palette after you make a change and want to see its results. 

This is where we catch any errors that get thrown from running prettier: https://github.com/prettier/prettier-atom/blob/master/src/executePrettier/executePrettierOnBufferRange.js#L22

Then this is where we handle it: https://github.com/prettier/prettier-atom/blob/master/src/executePrettier/handleError.js

**Comment by robwise** [comment]
@chmac I just released 0.37.0, can you try that version and see if it makes any difference?

**Comment by chmac** [comment]
@robwise Awesome, will do. Will be back at my machine Tuesday and will report back then...

**Comment by chmac** [comment]
@robwise Took a few days, but it looks like there's no change on my system. I saw no linter error today but the code was broken, so my app was crashing, and it took me a minute to figure out why. I'm guessing that means the issue persists. Will try to find time to get into the debugging steps you recommended.

**Comment by chmac** [comment]
I thought I had found a reproduction, because I have a file which shows no linter errors, but which will not format. I tried to copy the file elsewhere so I could strip out pieces and see if I could figure out what was causing the issue. But when I opened the file in a different location, linting errors show up. Also, if I close the original file and reopen it, the linting errors show up.

At best its intermittent, sometimes I see the error marked on the line with a red dot in the left column, and sometimes I see a `1` in the bottom status bar of the atom window showing me 1 linter error. But sometimes I see two errors, and sometimes the red dot does not appear.

I'm guessing the issue might be caused by some interaction of the packages I have installed. Does that sound possible? I've been experimenting with the `vim-mode-plus` package for a while now, which seems to introduce pretty significant changes to atom's behaviour. Maybe that's the culprit? Otherwise I have 111 packages installed, so could take a while to track down...

**Comment by robwise** [comment]
@chmac Hahaha, well I use vim-mode-plus as well (I can't live without it). Come to think of it, I _have_ been noticing strange counts in my linter but no actual errors that I can find. Some people have reported success with getting errors not to happen by manually installing `prettier` and `prettier-eslint` in their package.json (prettier-atom is smart enough to pick these up).

**Comment by posebear1990** [comment]
I have same problem, and this is my option: 
```
Atom version: 1.19.0
prettier-atom version: 0.37.0
prettier version: 1.5.3
prettier-eslint version: 6.4.2
prettier-atom configuration: {
  "formatOnSaveOptions": {
    "enabled": true,
    "isDisabledIfNotInPackageJson": true,
    "showInStatusBar": true,
    "respectEslintignore": true,
    "javascriptScopes": [
      "source.js",
      "source.jsx",
      "source.js.jsx",
      "source.babel",
      "source.js-semantic",
      "text.html.basic",
      "text.html.vue"
    ],
    "typescriptScopes": [
      "source.ts",
      "source.tsx",
      "source.ts.tsx"
    ],
    "cssScopes": [
      "source.css",
      "source.less",
      "source.css.less",
      "source.scss",
      "source.css.scss"
    ],
    "jsonScopes": [
      "source.json"
    ],
    "graphQlScopes": [
      "source.graphql"
    ],
    "excludedGlobs": [],
    "whitelistedGlobs": []
  },
  "prettierOptions": {
    "parser": "flow",
    "singleQuote": false,
    "bracketSpacing": true,
    "semi": true,
    "useTabs": false,
    "jsxBracketSameLine": false,
    "printWidth": 80,
    "tabWidth": "auto",
    "trailingComma": "none"
  },
  "useEslint": true,
  "useEditorConfig": true,
  "prettierEslintOptions": {
    "prettierLast": false
  }
}
```

**Comment by johanhenrikssn** [comment]
I had the same problem, but I had the linter package disabled. Enabling it gave me errors, but after uninstalling it, I got a prompt saying that prettier-atom wants to install the linter package and now it's working.

**Comment by robwise** [comment]
Yes `linter` is required for this package

**Comment by gperdomor** [comment]
I'm using `Nuclide` with nuclide diagnostic which is incompatible with `linter`... I'm getting this error, should be nice that package detect which linter is installed
<img width="580" alt="screen shot 2017-08-12 at 4 31 18 pm" src="https://user-images.githubusercontent.com/371939/29244028-43639af2-7f7c-11e7-9ca2-3dc79d54af08.png">

**Comment by chmac** [comment]
@gperdomor Personally, not sure if I understand your issue, but maybe it belongs in a new issue? Doesn't sound like the same problem as here?

@robwise I tried @johanhenrikssn's strategy of removing the linter package and having it reinstalled by the prompt as in @gperdomor's screenshot. It installed linter version `2.0.0`, and I get prompted to upgrade to `2.2.0`. So far I've avoided that update and I always seem to be seeing linting errors. Unclear if it's related to the version change or not, but it seems to be working for now. Not sure if that's useful in trying to figure out what the issue is or not.

Still have in mind to try the debugging approach you posted, but I guess laziness will prevent me from doing that unless something breaks again. :-)

**Comment by chmac** [comment]
I take that back, I'm seeing the same problem as before with linter `2.0.0`, so I'll upgrade. :-)

Here's the smallest reproduction I could find that consistently breaks prettier but doesn't show a linter error.

```es6
const foo = bar => _.identity({baz: bar})
  return { baz: bar };
};
```

Steps to reproduce:

1) Open a new file in atom
2) Set the type to babel es6 (you need the `language-babel` package installed)
3) Paste the code above
4) Run the "Prettier: Format" command

When I do that, I can restart atom and still not get any linting errors. However, I noticed that if I save the file then the linter errors do show. Normally an atom restart will show errors, but maybe only in files which have been saved to disk.

**Comment by robwise** [comment]
@chmac We currently have a workaround for unsaved files because so many of our options require looking things up relative to the file path (eslint, eslintignore, making sure prettier is in the dependencies, etc.). So we basically just exit early if the file is not saved. However, I can see how this is confusing, so I'm open to coding up an alternative solution. Maybe we just fall back to some sort of default rules in the case where we can't find a current file path?

**Comment by chmac** [comment]
@robwise Aha, then my reproduction strategy is broken! I saw the error on this code in a file that had been saved, but was currently unsaved when it was in that state. I try to use format before saving so that my rebuild process doesn't kick off with a broken file.

So the process aborts if the file has never been saved, is that correct? But once the file has been saved once, it will run as normal. Hmm, harder to reproduce consistently I guess...

**Comment by robwise** [comment]
> So the process aborts if the file has never been saved, is that correct? But once the file has been saved once, it will run as normal.

Crap actually I think I told you the wrong thing. I was thinking of format on save, not manual save. So yes, this should be erroring and this does reproduce the bug! I will work on a fix!

**Comment by chmac** [comment]
@robwise Thanks for the update on this one. Alas, I suspect this was not my issue as I'm 99% sure I was seeing the same behaviour on saved and unsaved files. It's *very* rare that I create a file which doesn't have a filename, I usually create files by name. So unfortunately I guess my original issue is still open.

**Comment by robwise** [comment]
Okay, if you get a reproducible case please let me know and I will fix.

**Comment by robwise** [comment]
Should be fixed in #321
